package me.friwi.jcefmaven;

/**
 * Native JCEF bundle<br/>
 * <br/>
 * Platform: <code>{platform}</code><br/>
 * Version: <code>{release_tag}</code><br/>
 * Generated by: <a href="https://github.com/jcefmaven/jcefmaven">https://github.com/jcefmaven/jcefmaven</a><br/>
 * <br/>
 * Please refer to the url above for usage instructions.<br/>
 * <br/>
 * Made with love by @FriwiDev.
 *
 * @author Fritz Windisch
 */
public class CefNativeBundle {
   /**
    * Private default constructor to prevent creation of instances.
    */
   private CefNativeBundle(){
   }
   
   /**
    * Returns the platform of this native bundle.
    * Does not require build_meta.json to be on classpath.
    * @return <code>{platform}</code>
    */
   public static String getPlatformString(){
       return "{platform}";
   }
   
   /**
    * Returns the release tag of this native bundle.
    * Does not require build_meta.json to be on classpath.
    * @return <code>{release_tag}</code>
    */
   public static String getReleaseTagString(){
       return "{release_tag}";
   }
} 
